### Event
POST http://localhost:3333/event
Content-Type: application/json

{
  "name": "aaaaaaaaa",
  "address": "Rua Janary Nunes, 170 - Infraero, Macapá - AP",
  "cep": "68908-876",
  "city": "Macapá",
  "state": "AP",
  "complement": "Área Comercial",
  "coverImage": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/a7/9e/3d/fachada.jpg?w=700&h=-1&s=1",
  "description": "Evento de Tecnologia super bacana",
  "neighborhood": "Infraero",
  "number": "170",
  "privacy": "private",
  "startDate": "2023-08-20T12:00:00.000Z",
  "startTime": "10:00"
}
### 
GET http://localhost:3333/event
###
GET http://localhost:3333/event/search?name=upda
###
GET http://localhost:3333/event/7ef84b30-2f64-466d-84c2-7889e7ad1094
###
PUT http://localhost:3333/event
Content-Type: application/json

{
  "id": "7ef84b30-2f64-466d-84c2-7889e7ad1094",
  "name": "Updated Event",
  "address": "Rua Janary Nunes, 170 - Infraero, Macapá - AP",
  "cep": "68908-876",
  "city": "Macapá",
  "state": "AP",
  "complement": "Área Comercial",
  "coverImage": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/a7/9e/3d/fachada.jpg?w=700&h=-1&s=1",
  "description": "Evento de Tecnologia super bacana",
  "neighborhood": "Infraero",
  "number": "170",
  "privacy": "public",
  "startDate": "2023-08-20T12:00:00.000Z",
  "startTime": "10:00"
}
###
DELETE http://localhost:3333/event?id=f6e58478-5366-416b-9653-4f5fe61ff7d0