### Event
POST http://localhost:3333/event
Content-Type: application/json

{
  "name": "3 Direct",
  "address": "Rua Janary Nunes, 170 - Infraero, Macapá - AP",
  "cep": "68908-876",
  "city": "Rio de Janeiro",
  "state": "RJ",
  "complement": "Área Comercial",
  "coverImage": "https://cdn.jornaldebrasilia.com.br/wp-content/uploads/2023/03/23165017/ccxp.jpg",
  "description": "Evento de Tecnologia super bacana",
  "neighborhood": "Infraero",
  "number": "170",
  "privacy": "private",
  "startDate": "2023-09-07T12:00:00.000Z",
  "startTime": "10:00"
}
### 
GET http://localhost:3333/event
###
GET http://localhost:3333/event/search?name=upda
###
GET http://localhost:3333/event/7ef84b30-2f64-466d-84c2-7889e7ad1094
###
PUT http://localhost:3333/event
Content-Type: application/json

{
  "id": "24c00c64-35a7-4134-8a1b-6927f7dc80bc",
   "name": "Nintendo Direct",
  "address": "Rua Janary Nunes, 170 - Infraero, Macapá - AP",
  "cep": "68908-876",
  "city": "Rio de Janeiro",
  "state": "RJ",
  "complement": "Área Comercial",
  "coverImage": "https://img.olhardigital.com.br/wp-content/uploads/2020/07/20200720114613.jpg",
  "description": "Evento de Tecnologia super bacana",
  "neighborhood": "Infraero",
  "number": "170",
  "privacy": "private",
  "startDate": "2023-09-07T12:00:00.000Z",
  "startTime": "10:00"
}
###
DELETE http://localhost:3333/event?id=f6e58478-5366-416b-9653-4f5fe61ff7d0